import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'fr');
  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('lang', newLang);
  };

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  const toggleLanguage = () => {};

  const t = (key) => {
    const translations = {
      fr: {
        dashboard: 'Tableau de bord',
        students: 'Étudiants',
        teachers: 'Enseignants',
        revenue: 'Chiffre d\'Affaires',
        attendance: 'Présence',
        recent_activity: 'Activités Récentes',
        quick_actions: 'Actions Rapides',
        add_student: 'Ajouter un Étudiant',
        mark_attendance: 'Marquer Présence',
        generate_report: 'Générer Rapport',
        search: 'Rechercher...',
        profile: 'Profil',
        logout: 'Déconnexion',
        welcome: 'Bienvenue',
        french: 'Français',
        monday: 'Lundi',
        tuesday: 'Mardi',
        wednesday: 'Mercredi',
        thursday: 'Jeudi',
        friday: 'Vendredi',
        saturday: 'Samedi',
        sunday: 'Dimanche',
        academics: 'Gestion Académique',
        hr: 'Ressources Humaines',
        payroll: 'Paie',
        leave_requests: 'Demandes de Congé',
        timetable: 'Emploi du temps',
        exams: 'Examens',
        admissions: 'Admissions',
        inventory: 'Inventaire',
        events: 'Événements',
        learning: 'E-learning',
        reports: 'Rapports',
        grades: 'Notes & Résultats',
        marks: 'Saisie des Notes',
        report_cards: 'Bulletins de Notes',
        schedule_exam: 'Planifier Examen',
        library_inventory: 'Inventaire Livres',
        borrowing: 'Emprunts',
        overdue: 'Retards',
        messaging: 'Messages',
        announcements: 'Annonces',
        bus_routes: 'Itinéraires Bus',
        gps_tracking: 'Suivi GPS',
        drivers: 'Chauffeurs',
        invoices: 'Factures',
        fees_structure: 'Structure des Frais',
        total_revenue: 'Revenu Total',
        pending_fees: 'Frais en Attente',
        collection_rate: 'Taux de Recouvrement',
        scholarships: 'Bourses',
        paid: 'Payé',
        pending: 'En attente',
        total_assets: 'Total des Actifs',
        consumables: 'Consommables',
        stock_alerts: 'Alertes de Stock',
        maintenance: 'Entretien',
        categories: 'Catégories',
        low_stock: 'Stock Faible',
        performance_heatmap: 'Carte de Performance',
        attendance_trends: 'Tendances de Présence',
        financial_forecast: 'Prévisions Financières',
        overview: 'Vue d\'ensemble',
        admin_dashboard_subtitle: 'Pilotage de l\'établissement Atlas Academy',
        management_actions: 'Actions de Gestion',
        user_accounts: 'Comptes Utilisateurs',
        user_accounts_desc: 'Admin, Profs, Parents',
        hr_staff: 'RH & Personnel',
        hr_staff_desc: 'Équipe Atlas Academy',
        enrollments: 'Inscriptions',
        enrollments_desc: 'Nouveaux Élèves',
        finances: 'Finances',
        finances_desc: 'Facturation & Paie',
        attendance_management: 'Présences',
        attendance_desc: 'Suivi Quotidien',
        messaging: 'Messagerie',
        messaging_desc: 'Communications',
        messaging_desc: 'Communications',
        parents: 'Parents',
        subjects: 'Matières',
        library_alert: 'Attention : Retard Bibliothèque',
        view_borrows: 'Voir Mes Emprunts',
        student_space: 'Espace Étudiant',
        academic_year: 'Année Académique',
        status: 'Statut',
        active: 'Actif',
        upcoming_exams: 'Examens à venir',
        view_all: 'Tout voir',
        no_scheduled_exams: 'Pas d\'examens programmés',
        attendance_tracking: 'Suivi des Présences',
        no_records_yet: 'Pas encore de relevés',
        my_school: 'Mon École',
        my_library: 'Ma Bibliothèque',
        contact_admin: 'Contact Admin',
        account_issue: 'Un problème avec votre compte ?',
        send_message: 'Envoyer message',
        financial_dashboard: 'Tableau de Bord Financier',
        finance_subtitle: 'Gérez les revenus, les frais de scolarité et les analyses budgétaires',
        export_csv: 'Exporter Excel',
        generate_invoice: 'Générer Facture',
        invoices_receipts: 'Factures & Reçus',
        hr_subtitle: 'Gestion du personnel et des comptes d\'administration',
        add_employee: 'Déclarer un employé',
        staff_directory: 'Registre du Personnel',
        user_management: 'Gestion des Comptes',
        user_management_subtitle: 'Créer et gérer les comptes élèves, enseignants et parents',
        add_user: 'Ajouter un Utilisateur',
        school_discussions: 'Discussions scolaires',
        new_discussion: 'Nouvelle Discussion',
        call_roll: 'Faire l\'appel',
        enter_grades: 'Saisir les Notes',
        request_leave: 'Demander un Congé',
        contact_admin: 'Contacter l\'Admin',
        attendance_reports: 'Rapports d\'Assiduité',
        class_progression: 'Progression des Classes',
        your_performances: 'Vos performances',
        upcoming_events: 'Événements à Venir',
        recent_tasks: 'Tâches Récentes',
        my_documents: 'Mes Documents',
        absences: 'Absences',
        sessions_scheduled: 'séances programmées cette semaine',
        no_sessions: 'Aucune séance programmée pour le moment.',
        today_classes: 'Cours d\'Aujourd\'hui',
        manage_class: 'Gérer la classe',
        absent: 'absents',
        you_have: 'Vous avez',
        monthly_salary: 'Salaire Mensuel',
        my_leaves: 'Mes Congés',
        requests_status: 'Demandes & Statut',
        room: 'Salle',
        no_requests: 'Aucune demande',
        new_request: 'Nouvelle Demande',
        salary_details: 'Détails Salaire',
        base_salary: 'Salaire de Base',
        month: 'mois',
        last_payment: 'Dernier Paiement',
        payroll_info: 'Les fiches de paie sont disponibles auprès de l\'administration RH.',
        my_students: 'Mes Étudiants',
        no_students_found: 'Aucun élève trouvé',
        view_all_students: 'Voir tous les élèves',
        subjects_taught: 'Matières Enseignées',
        overdue_notice_1: 'Vous avez',
        overdue_notice_2: 'livre(s) en retard. Merci de les retourner au plus vite.'
      },
      en: {
        dashboard: 'Dashboard',
        students: 'Students',
        teachers: 'Teachers',
        revenue: 'Revenue',
        attendance: 'Attendance',
        recent_activity: 'Recent Activity',
        quick_actions: 'Quick Actions',
        add_student: 'Add Student',
        mark_attendance: 'Mark Attendance',
        generate_report: 'Generate Report',
        search: 'Search...',
        profile: 'Profile',
        logout: 'Logout',
        welcome: 'Welcome',
        english: 'English',
        monday: 'Monday',
        tuesday: 'Tuesday',
        wednesday: 'Wednesday',
        thursday: 'Thursday',
        friday: 'Friday',
        saturday: 'Saturday',
        sunday: 'Sunday',
        academics: 'Academics',
        hr: 'Human Resources',
        payroll: 'Payroll',
        leave_requests: 'Leave Requests',
        timetable: 'Timetable',
        exams: 'Exams',
        admissions: 'Admissions',
        inventory: 'Inventory',
        events: 'Events',
        learning: 'E-learning',
        reports: 'Reports',
        grades: 'Grades & Results',
        marks: 'Enter Marks',
        report_cards: 'Report Cards',
        schedule_exam: 'Schedule Exam',
        library_inventory: 'Library Inventory',
        borrowing: 'Borrowing',
        overdue: 'Overdue',
        messaging: 'Messaging',
        announcements: 'Announcements',
        bus_routes: 'Bus Routes',
        gps_tracking: 'GPS Tracking',
        drivers: 'Drivers',
        invoices: 'Invoices',
        fees_structure: 'Fees Structure',
        total_revenue: 'Total Revenue',
        pending_fees: 'Pending Fees',
        collection_rate: 'Collection Rate',
        scholarships: 'Scholarships',
        paid: 'Paid',
        pending: 'Pending',
        total_assets: 'Total Assets',
        consumables: 'Consumables',
        stock_alerts: 'Stock Alerts',
        maintenance: 'Maintenance',
        categories: 'Categories',
        low_stock: 'Low Stock',
        performance_heatmap: 'Performance Heatmap',
        attendance_trends: 'Attendance Trends',
        financial_forecast: 'Financial Forecast',
        overview: 'Overview',
        admin_dashboard_subtitle: 'Atlas Academy Management Dashboard',
        management_actions: 'Management Actions',
        user_accounts: 'User Accounts',
        user_accounts_desc: 'Admins, Teachers, Parents',
        hr_staff: 'HR & Staff',
        hr_staff_desc: 'Atlas Academy Team',
        enrollments: 'Enrollments',
        enrollments_desc: 'New Students',
        finances: 'Finances',
        finances_desc: 'Invoicing & Payroll',
        attendance_management: 'Attendance',
        attendance_desc: 'Daily Tracking',
        messaging_desc: 'Communications',
        messaging_desc: 'Communications',
        parents: 'Parents',
        subjects: 'Subjects',
        library_alert: 'Warning: Library Overdue',
        view_borrows: 'View My Borrows',
        student_space: 'Student Space',
        academic_year: 'Academic Year',
        status: 'Status',
        active: 'Active',
        upcoming_exams: 'Upcoming Exams',
        view_all: 'View All',
        no_scheduled_exams: 'No scheduled exams',
        attendance_tracking: 'Attendance Tracking',
        no_records_yet: 'No records yet',
        my_school: 'My School',
        my_library: 'My Library',
        contact_admin: 'Contact Admin',
        account_issue: 'Account issue?',
        send_message: 'Send Message',
        financial_dashboard: 'Financial Dashboard',
        finance_subtitle: 'Manage revenue, tuition fees, and budget analytics',
        export_csv: 'Export Excel',
        generate_invoice: 'Generate Invoice',
        invoices_receipts: 'Invoices & Receipts',
        hr_subtitle: 'Staff and administration account management',
        add_employee: 'Add Employee',
        staff_directory: 'Staff Directory',
        user_management: 'User Management',
        user_management_subtitle: 'Create and manage student, teacher, and parent accounts',
        add_user: 'Add User',
        school_discussions: 'School Discussions',
        new_discussion: 'New Discussion',
        call_roll: 'Call Roll',
        enter_grades: 'Enter Grades',
        request_leave: 'Request Leave',
        contact_admin: 'Contact Admin',
        attendance_reports: 'Attendance Reports',
        class_progression: 'Class Progression',
        your_performances: 'Your Performances',
        upcoming_events: 'Upcoming Events',
        recent_tasks: 'Recent Tasks',
        my_documents: 'My Documents',
        absences: 'Absences',
        sessions_scheduled: 'sessions scheduled this week',
        no_sessions: 'No sessions scheduled currently.',
        today_classes: 'Today\'s Classes',
        manage_class: 'Manage Class',
        absent: 'absent',
        you_have: 'You have',
        monthly_salary: 'Monthly Salary',
        my_leaves: 'My Leaves',
        requests_status: 'Requests & Status',
        room: 'Room',
        no_requests: 'No requests',
        new_request: 'New Request',
        salary_details: 'Salary Details',
        base_salary: 'Base Salary',
        month: 'month',
        last_payment: 'Last Payment',
        payroll_info: 'Payslips are available at the HR administration office.',
        my_students: 'My Students',
        no_students_found: 'No students found',
        view_all_students: 'View all students',
        subjects_taught: 'Subjects Taught',
        overdue_notice_1: 'You have',
        overdue_notice_2: 'overdue book(s). Please return them ASAP.'
      }
    };
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, dir, toggleLanguage, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
